const games = [
  { title: 'Kenyan Jewel Crush', type: 'Puzzle / Casual', copy: 'A bright, satisfying match-three journey inspired by the color and rhythm of Kenya.', color: '#d9f27c', mark: 'KJ', url: 'https://play.google.com/store/apps/details?id=com.lightspeedlabs.kenyanjewelcrush' },
  { title: 'Siaka', type: 'Arcade / Action', copy: 'Fast hands. Sharp instincts. A compact arcade challenge made for repeat runs.', color: '#5eead4', mark: 'S', url: 'https://play.google.com/store/apps/details?id=com.lightspeedlabs.siaka' },
  { title: 'Sweet Swap Saga', type: 'Puzzle / Adventure', copy: 'Swap, solve, and chase the next sweet high score in this colorful saga.', color: '#ff9f80', mark: 'SS', url: 'https://play.google.com/store/apps/details?id=com.lightspeedlabs.sweetswapsaga' },
]

const services = ['Product design & engineering', 'Mobile apps & games', 'Blockchain experiences', 'Strategy for ambitious teams']

export default function Home() {
  return (
    <main>
      <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
        <a href="#top" className="flex items-center gap-3 font-semibold tracking-tight"><span className="relative flex size-9 items-center justify-center overflow-hidden rounded-full bg-[var(--kenya-red)] text-sm font-bold text-[var(--foreground)]"><span className="absolute inset-x-0 top-0 h-1/3 bg-[var(--background)]" /><span className="absolute inset-x-0 bottom-0 h-1/3 bg-[var(--kenya-green)]" /><span className="relative">L</span></span><span>LIGHTSPEED <span className="text-[var(--cyan)]">LABS</span></span></a>
        <nav className="hidden items-center gap-8 text-sm text-[var(--muted)] md:flex"><a href="#work" className="transition hover:text-[var(--foreground)]">Work</a><a href="#studio" className="transition hover:text-[var(--foreground)]">Studio</a><a href="#contact" className="transition hover:text-[var(--foreground)]">Contact</a></nav>
        <a href="#contact" className="rounded-full border border-[var(--line)] px-4 py-2 text-sm transition hover:border-[var(--cyan)] hover:text-[var(--cyan)]">Start a project <span aria-hidden="true">↗</span></a>
      </header>
      <div aria-hidden="true" className="mx-6 h-1 overflow-hidden rounded-full bg-[var(--background)] lg:mx-10"><div className="grid h-full grid-cols-5"><span className="bg-[var(--background)]" /><span className="bg-[var(--kenya-red)]" /><span className="bg-[var(--foreground)]" /><span className="bg-[var(--kenya-red)]" /><span className="bg-[var(--kenya-green)]" /></div></div>

      <section id="top" className="mx-auto max-w-7xl px-6 pb-24 pt-20 lg:px-10 lg:pb-36 lg:pt-32">
        <p className="mb-8 font-mono text-xs uppercase tracking-[0.28em] text-[var(--cyan)]">Independent digital studio · Nairobi / Everywhere</p>
        <h1 className="max-w-5xl text-balance text-6xl font-semibold leading-[0.95] tracking-[-0.07em] md:text-8xl lg:text-[9.5rem]">We make<br /><span className="text-[var(--cyan)]">what&apos;s next.</span></h1>
        <div className="mt-12 flex max-w-2xl flex-col gap-8 md:ml-auto md:mr-10 md:flex-row md:items-end md:justify-between"><p className="max-w-sm text-lg leading-relaxed text-[var(--muted)]">Lightspeed Labs creates software, games, apps, and blockchain experiences for people moving culture forward.</p><a href="#work" className="group flex size-24 shrink-0 items-center justify-center rounded-full bg-[var(--lime)] text-center text-sm font-semibold text-[var(--background)] transition group-hover:scale-105">See our<br />work <span aria-hidden="true">↓</span></a></div>
      </section>

      <section id="work" className="border-y border-[var(--line)] bg-[var(--panel)] px-6 py-20 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mb-12 flex items-end justify-between"><div><p className="mb-4 font-mono text-xs uppercase tracking-[0.25em] text-[var(--muted)]">01 / Selected work</p><h2 className="text-4xl font-semibold tracking-[-0.05em] md:text-6xl">Play, on purpose.</h2></div><a className="hidden text-sm text-[var(--cyan)] md:block" href="https://play.google.com/store/apps/dev?id=8973591659457970823&hl=en_US" target="_blank" rel="noreferrer">View Google Play studio ↗</a></div><div className="grid gap-5 lg:grid-cols-3">{games.map((game) => <a key={game.title} href={game.url} target="_blank" rel="noreferrer" className="group overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--background)] transition hover:-translate-y-1 hover:border-[var(--cyan)]"><div className="flex aspect-[1.1] items-end justify-between p-6" style={{ background: `linear-gradient(135deg, ${game.color} 0%, #17272a 58%, #071014 100%)` }}><span className="text-7xl font-semibold tracking-[-0.09em] text-[var(--background)] opacity-80">{game.mark}</span><span className="rounded-full bg-[var(--background)]/80 px-3 py-1 font-mono text-[10px] uppercase tracking-widest text-[var(--foreground)]">Google Play ↗</span></div><div className="flex flex-col gap-4 p-6"><div><p className="mb-2 font-mono text-[10px] uppercase tracking-widest text-[var(--cyan)]">{game.type}</p><h3 className="text-2xl font-medium tracking-tight">{game.title}</h3></div><p className="text-sm leading-relaxed text-[var(--muted)]">{game.copy}</p></div></a>)}</div></div></section>

      <section id="studio" className="mx-auto grid max-w-7xl gap-16 px-6 py-24 lg:grid-cols-[0.9fr_1.1fr] lg:px-10 lg:py-32"><div><p className="mb-4 font-mono text-xs uppercase tracking-[0.25em] text-[var(--muted)]">02 / What we do</p><h2 className="max-w-md text-5xl font-semibold leading-none tracking-[-0.06em] md:text-7xl">Small team.<br /><span className="text-[var(--cyan)]">Big velocity.</span></h2></div><div className="flex flex-col gap-0">{services.map((service, i) => <div key={service} className="flex items-center justify-between border-t border-[var(--line)] py-6 text-xl md:text-2xl"><span>{service}</span><span className="font-mono text-xs text-[var(--muted)]">0{i + 1}</span></div>)}<p className="mt-8 max-w-lg text-base leading-relaxed text-[var(--muted)]">We partner with founders, brands, and bold teams to turn rough ideas into products people want to use. From the first sketch to the next million users.</p></div></section>

      <section id="contact" className="border-t border-[var(--line)] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><p className="mb-8 font-mono text-xs uppercase tracking-[0.25em] text-[var(--cyan)]">03 / Let&apos;s build</p><div className="flex flex-col gap-10 md:flex-row md:items-end md:justify-between"><h2 className="max-w-3xl text-5xl font-semibold leading-none tracking-[-0.06em] md:text-8xl">Have a good<br /><span className="text-[var(--lime)]">idea?</span></h2><a href="mailto:hello@lightspeedlabs.dev" className="rounded-full bg-[var(--cyan)] px-6 py-4 font-semibold text-[var(--background)] transition hover:bg-[var(--lime)]">hello@lightspeedlabs.dev ↗</a></div></div></section>

      <footer className="mx-auto flex max-w-7xl flex-col gap-5 border-t border-[var(--line)] px-6 py-8 text-sm text-[var(--muted)] md:flex-row md:items-center md:justify-between lg:px-10"><p>© 2026 Lightspeed Labs. Built for the curious.</p><div className="flex gap-6"><a href="https://play.google.com/store/apps/dev?id=8973591659457970823&hl=en_US" target="_blank" rel="noreferrer" className="transition hover:text-[var(--foreground)]">Google Play ↗</a><a href="mailto:hello@lightspeedlabs.dev" className="transition hover:text-[var(--foreground)]">Email ↗</a></div></footer>
    </main>
  )
}
